name: Browser Actions Workflow
on:
  workflow_dispatch:
    inputs:
      browser-type:
        description: 'The type of browser to set up'
        required: true
        default: 'Chrome'
        options: ['Chrome', 'Firefox', 'Edge']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up browser
        run: |
          case ${{ github.event.inputs.browser-type }} in
          'Chrome')
            browser_type='chromium'
            setup_action='actions/setup-chrome@v3'
            ;;
          'Firefox')
            browser_type='firefox'
            setup_action='actions/setup-firefox@v3'
            ;;
          'Edge')
            browser_type='webkit'
            setup_action='actions/setup-edge@v3'
            ;;
          esac
          echo "::set-output name=browser-type::$browser_type"
          echo "::set-output name=setup-action::$setup_action"
        id: setup_browser

      - name: Use browser
        uses: ${{ steps.setup_browser.outputs.setup-action }}
        with:
          version: 'latest'
          headless: true
          start-url: https://example.com