name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World!"
      - name: Multiline Command
        run: |
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v
          echo "Java version:"
          java --version