name: Test
on:
  push:
    branches:
      - 'main'
      - 'test_workflow'
  workflow_dispatch:
    inputs:
      ENV:
        type: choice
        required: true
        description: 'Please, choose environment:'
        default: 'qa'
        options:
          - 'qa'
          - 'dev'
          - 'ct'
          - 'prod'
      TYPE:
        type: choice
        required: true
        description: 'Please, choose environment:'
        default: 'type01'
        options:
          - 'type01'
          - 'type02'
jobs:
  test-summary:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Get ENV value from ${{github.event.inputs.ENV}}"
      - run: echo "Get TYPE value from ${{github.event.inputs.TYPE}}"