name: 4. DEMO - Automation Test Workflow - UI Selenium JS
on:
  workflow_dispatch:
    name: on-demand
    inputs:
      ENV:
        type: choice
        required: true
        description: 'Please, choose environment:'
        default: 'QA'
        options:
          - DEV
          - QA
          - CT
          - PROD
      TEST_TYPE:
        type: choice
        required: true
        description: 'Please, choose test type:'
        default: 'smoke'
        options:
          - smoke
          - sanity
          - regression
      BROWSER:
        type: choice
        required: true
        description: 'Please, choose browser:'
        default: 'Chrome'
        options:
          - Chrome
          - Firefox
          - Edge
jobs:
  test-summary:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Actor is ${{ github.actor }}"
      - run: echo "Branch is ${{github.ref}}"
      - run: echo "BDD tag is @${{github.event.inputs.TEST_TYPE}}_${{github.event.inputs.ENV}}"

  regression-test:
    runs-on: ubuntu-latest
    needs: test-summary
    steps:
      - name: 2.1 Checkout code
        uses: actions/checkout@v3

      - name: 2.2 Convert input strings to lowercase
        id: toLowerCase
        run: | 
          echo "::set-output name=lowerCase_env::${LOWERCASE_ENV,,}"
          echo ${{steps.toLowerCase.outputs.lowerCase_env}}
          echo "::set-output name=lowerCase_test_type::${UPPERCASE_TEST_TYPE^^}"
          echo ${{steps.toLowerCase.outputs.lowerCase_test_type}}
          echo "::set-output name=lowerCase_browser::${LOWERCASE_BROWSER,,}"
          echo ${{steps.toLowerCase.outputs.lowerCase_browser}}
        env:
          LOWERCASE_ENV: ${{github.event.inputs.ENV}}
          UPPERCASE_TEST_TYPE: ${{github.event.inputs.TEST_TYPE}}
          LOWERCASE_BROWSER: ${{github.event.inputs.BROWSER}}

      - name: 2.3 Set up Node JS
        uses: actions/setup-node@v3
        with:
          node-version: '16.16'

      - name: 2.4 Set up browser
        run: |
          case ${{ github.event.inputs.browser-type }} in
          'Chrome')
            setup_action='actions/setup-chrome@v3'
            ;;
          'Firefox')
            setup_action='actions/setup-firefox@v3'
            ;;
          'Edge')
            setup_action='actions/setup-edge@v3'
            ;;
          esac
          echo "::set-output name=setup-action::$setup_action"
        id: setup_browser

      - name: Set up Chrome
        if: steps.setup_browser.outputs.setup-action == 'actions/setup-chrome@v3'
        uses: actions/setup-chrome@v3

      - name: Set up Firefox
        if: steps.setup_browser.outputs.setup-action == 'actions/setup-firefox@v3'
        uses: actions/setup-firefox@v3

      - name: Set up Edge
        if: steps.setup_browser.outputs.setup-action == 'actions/setup-edge@v3'
        uses: actions/setup-edge@v3
#        uses: browser-actions/setup-chrome@v1
#      - run: chrome --version
        # run: echo "The browser is ${{github.event.inputs.BROWSER}}"
        # uses: actions/setup-@v3

      # - name: 2.5 Config .env file
      # - name: 2.6 Test run
      # - name: 2.7 Upload report artifact
